name:                nwlisp
version:             0.1.0.0
github:              "TorNATO-PRO/nwlisp"
license:             BSD3
author:              "Nathan Waltz"
maintainer:          "waltznr@gmail.com"
copyright:           "Copyright (c) 2023"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/TorNATO-PRO/nwlisp#readme>

dependencies:
- base >= 4.7 && < 5
- free >= 5.0.2
- containers >= 0.4.0.0
- transformers >= 0.6.1.0
- attoparsec >= 0.14.4
- text >= 1.2.3.2
- deepseq >= 1.3.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  nwlisp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nwlisp

tests:
  nwlisp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nwlisp
